-- Criação da Tabela 
CREATE TABLE PRODUTO_TECNICO (
    ID                          INTEGER NOT NULL,
    NUMERO_REGISTRO             VARCHAR(20) NOT NULL,
    MARCA_COMERCIAL             VARCHAR(500),
    CLASSE_AGRONOMICA           VARCHAR(300),
    TITULAR_REGISTRO            VARCHAR(200),
    CLASSIFICACAO_TOXICOLOGICA  VARCHAR(100),
    CLASSIFICACAO_AMBIENTAL     VARCHAR(100),
    URL_AGROFIT                 VARCHAR(300),
    DATA_CONSULTA               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Chave primária
ALTER TABLE PRODUTO_TECNICO
ADD CONSTRAINT PK_PRODUTO_TECNICO
PRIMARY KEY (ID);

-- Gerador do valor auto incrementado
CREATE GENERATOR GEN_PRODUTO_TECNICO_ID;

-- Trigger para autoincremento
SET TERM ^ ;
CREATE TRIGGER BI_PRODUTO_TECNICO
FOR PRODUTO_TECNICO
ACTIVE BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTO_TECNICO_ID, 1);
END^
SET TERM ; ^

-- indice para busca rápida
CREATE UNIQUE INDEX IDX_PRODUTO_TECNICO_REG
ON PRODUTO_TECNICO (NUMERO_REGISTRO);